### ISSUE TITLE
How do you use the signed urls?

### ISSUE THREAD

**Issue by matthewlal** [Bernix01/medusa-storage-supabase#20]
How do you use the signed urls? I reviewed the code, I assume it's to files that are uploaded in the /private folder of the bucket? Then these files auto delete after a specific time; does MedusaJS handle this somehow perhaps through the File Service interface? Also since the bucket is public does that mean there will be 2 links for private files? 1 link that shouldn't be shared and is hard to guess, and the 1 other link being the signed url?

**Comment by Bernix01** [comment]
Hello, afaik and according to what Medusa states in [the docs](https://docs.medusajs.com/development/file-service/create-file-service):

- There is no such thing as auto delete after some time
- Signed URLs are generated and used by Medusa in ways how Medusa sees fit (or if you call the method manually) so there is no control wether everything is a signed url or not.
- As the bucket is public yes, there will be two urls available with hard to guess and the signed one. You could change this behavior with bucket policies [see here](https://supabase.com/docs/guides/storage/security/access-control)
