### ISSUE TITLE
Plugin works locally but not when deployed

### ISSUE THREAD

**Issue by DanielHirunrusme** [Bernix01/medusa-storage-supabase#24]
I can successfully add images locally with this plugin, but it does not work when deployed. 

All my env variables are set properly. Not receiving any errors.

**Comment by Bernix01** [comment]
Hello, thanks for reaching out, can you add more context? Maybe enable debug in Medusa and see if there is any error thrown? 

Also just in case double check you env variables and bucket name.

I can't provide any assistance without more information and it's working just fine in my setup with railway as compute provider.
